# Generated by Django 4.2.2 on 2023-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_auto_20210505_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
